version: '3.8'

services:
  backend:
    image: injustic/multitripfinder-backend:1.0.5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tripDb:3306/MultiTripFinder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - ALGORITHM_OPTION=GOOGLE
      - AMADEUS_API_URL=https://test.api.amadeus.com/v2/shopping/flight-offers
      - FRONTEND_URL=http://mtf.norwayeast.cloudapp.azure.com
      - AMADEUS_CLIENT_ID=${AMADEUS_CLIENT_ID}
      - AMADEUS_CLIENT_SECRET=${AMADEUS_CLIENT_SECRET}
    depends_on:
      - tripDb
    networks:
      - app-network

  frontend:
    image: injustic/multitripfinder-frontend:1.1.2
    environment:
      - REACT_APP_GOOGLE_API_KEY=AIzaSyCsNLu69qSRJpeXQt0GXeHDVZ_mOFUagmY
    depends_on:
      - backend
    networks:
      - app-network

  tripDb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MultiTripFinder
    ports:
      - "3307:3306"
    volumes:
      - tripDb:/var/lib/mysql
      - /home/azureuser/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  tripDb:

networks:
  app-network: