version: '3'
services:
  backend:
    build:
      context: backend
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tripDb:3306/MultiTripFinder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - tripDb
  tripDb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MultiTripFinder
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - tripDb:/var/lib/mysql

volumes:
  tripDb:
